### ISSUE TITLE
Report: Wikimedia Hackathon 2023, Athens

### ISSUE THREAD

**Issue by tonythomas01** [wmhack2023/wmhack2023.github.io#43]
I wrote in Wordpress here: https://fosstalks.wordpress.com/2023/05/27/report-wikimedia-hackathon-2023-athens/ 

Will create a markdown PR soon.

**Comment by Greekforce1821** [comment]
Thank you very much for your contribution @tonythomas01 !!

**Comment by tonythomas01** [comment]
Thanks for merging @Greekforce1821. Wish I could test it locally. :-( For some reason, getting ruby set up did not go right.

**Comment by Greekforce1821** [comment]
You are very welcome! I did a few patches for your .md file because the panorama photo at the top was not showing up, and there was a need to add your github profile to the authors file in order to show up your proper name in your post. It is good now! Again, thank you very much for your contributions!!

![Screenshot_311](https://github.com/wmhack2023/wmhack2023.github.io/assets/33377581/95ee60fb-3dea-4524-a62a-9734f40e7705)
